# Generated by Django 2.2 on 2022-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='firm',
            field=models.CharField(choices=[('Nabor', 'nabor'), ('First', 'f'), ('Second', 's'), ('Third', 't'), ('Forth', 'f')], default='First', max_length=10),
        ),
    ]
