# Generated by Django 2.2 on 2022-07-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220723_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='firm',
            field=models.CharField(choices=[('ARM', 'ARMAF'), ('FLV', 'Flavia'), ('OROS', 'OROS'), ('HM', 'HAMIDI'), ('LT', 'Lattafa')], default='First', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=True, to='core.Brand'),
        ),
    ]
