# Generated by Django 2.2 on 2022-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220801_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='firm',
            field=models.CharField(choices=[('ARM', 'ARMAF'), ('FLV', 'Flavia'), ('OROS', 'OROS'), ('HM', 'HAMIDI'), ('LT', 'Lattafa'), ('NB', 'Наборы')], default='First', max_length=10),
        ),
    ]
