# Generated by Django 2.2 on 2022-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(choices=[('Man', 'man'), ('Wom', 'woman'), ('Nab', 'nabor'), ('UNI', 'unisex')], default='Man', max_length=3),
        ),
    ]
