# Generated by Django 2.2 on 2022-09-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220904_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='firm',
        ),
    ]
