# Generated by Django 2.2 on 2022-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_headerpictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderPictures',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=True, to='core.Category'),
        ),
    ]
